name: test build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.8, 3.9]
        cmake-version: [3.12.4]

    steps:
    - uses: actions/checkout@master
    - name: Get submodules
      run: |
        git submodule update --init --recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install libjpeg-dev libopencv-dev
    - name: Test hello-world build
      run: |
        cd examples/hello-world
        python project.py build
        python project.py clean
        python project.py distclean
        cd ../..
    - name: Test camera build
      run: |
        cd examples/camera
        python project.py build
        python project.py clean
        python project.py distclean
        cd ../..
    - name: Test nn_resnet build
      run: |
        cd examples/nn_resnet
        python project.py build
        python project.py clean
        python project.py distclean
        cd ../..
